from settingmanager import SettingManager
from setting import Setting
from settingdialog import SettingDialog
from bool import Bool
from color import Color
from double import Double
from integer import Integer
from string import String
from stringlist import Stringlist
