from .bool_widgets import CheckBoxBoolWidget, GroupBoxBoolWidget, CheckableBoolWidget
from .color_widgets import QgisColorWidget, StandardColorWidget
from .double_widgets import LineEditDoubleWidget, DoubleQgsScaleWidget, DoubleSpinBoxDoubleWidget
from .integer_widgets import LineEditIntegerWidget, SpinBoxIntegerWidget, ComboBoxIntegerWidget
from .stringlist_widgets import ListStringListWidget, TableWidgetStringListWidget, ButtonGroupStringListWidget
from .string_widgets import ComboMode, LineEditStringWidget, ButtonGroupStringWidget, ComboStringWidget, MapLayerComboStringWidget, FieldComboStringWidget, FileStringWidget, AuthConfigSelectStringWidget, ProjectionStringWidget
from .enum_widgets import ComboEnumWidget
